Feature/update texts
EyeSeeTea/notification-app pull request #12
Opened 2019-03-07 06:47 UTC by xurxodev

### :pushpin: References

* **Issue:** Close #6   

### :memo: Implementation

I have added new sections and subtitle for last fields using typography component applying styles according to the [material-ui  documentation](https://material-ui.com/style/typography/)

### :art: Screenshots
![psi notification settings app](https://user-images.githubusercontent.com/5593590/53937369-32f5cc00-40ad-11e9-9704-8b82665484c7.png)

### :fire: Is there anything the reviewer should know to test it?

### :bookmark_tabs: Others

2019-03-11 00:30 UTC, adrianq requested changes
@xurxodev Thanks for this! It looks good. I am just asking for some minor changes, mainly styling.
Btw, I saw your comment about gettext dependency. No worries about it. Dependencies change so often we have given up updating the README. Just some general guidelines but thanks for saying it!

2019-03-11 00:30 UTC, adrianq commented on src/components/NotificationsForm.js
> +                            {'DHIS can forward some or all of the messages that are sent to your '}
This needs to use i18n

2019-03-11 00:30 UTC, adrianq commented on src/components/NotificationsForm.js
> +                            {'DHIS Message forwarding'}
This needs to use i18n

2019-03-11 00:30 UTC, adrianq commented on src/components/NotificationsForm.js
> +                            {i18n.t('Ot-Out of @mention email notifications')}
This should be 'opt-out', right?

2019-03-11 00:30 UTC, adrianq commented on src/components/NotificationsForm.js
> +                            {i18n.t('Ot-Out of @mention email notifications')}
This should be 'Opt-Out', right?

2019-03-11 00:30 UTC, adrianq commented on src/components/NotificationsForm.js
> +                            {i18n.t('Enable SMS forwarding (All)')}
Can you add bold styling to titles as in the screenshot?

2019-03-11 00:30 UTC, adrianq commented on src/components/NotificationsForm.js
> +                        <Typography gutterBottom variant="h6" component="h3">
Can you please add some more top margin here so the section title doesn't look that close to the Phone field?

2019-03-12 05:49 UTC, xurxodev commented
@adrianq Done!

2019-03-12 09:07 UTC, adrianq approved these changes

2019-03-12 09:07 UTC, merged